FROM node:22

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install


COPY . .
COPY docker/.env .

RUN pnpm run build

ENV TZ=America/Sao_Paulo

ENV NODE_OPTIONS="--max-old-space-size=4096"

EXPOSE ${PORT}

CMD ["pnpm", "run", "start"]