services:

  queues-manager:
    image: isaias10/rabbit-easy
    container_name: queue-manager
    volumes:
      - ./queue-config.json:/config.json
    restart: always
    hostname: escoffier.queue
    ports:
      - "15673:15672"
      - "5673:5672"

    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASS}
    networks:
      - escoffier.network

  restaurant-db:
    image: postgres:15
    container_name: restaurant-db
    environment:
      POSTGRES_USER: ${DBR_USER}
      POSTGRES_PASSWORD: ${DBR_PASS}
      POSTGRES_DB: ${DBR_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./restaurant-db:/var/lib/postgresql/data
    restart: always

    networks:
      - escoffier.restaurant.network


networks:
  escoffier.network:
    driver: bridge

  escoffier.restaurant.network:
    driver: bridge