services:

  db:
    image: mongo:4.4
    restart: always
    hostname: escoffier.db

    volumes:
      - ./mongo-data:/data/db
  
    networks:
      - escoffier.net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  redis:
    image: redis
    hostname: ${REDIS_HOST}
    volumes:
      - ./redis-data:/data
    restart: always
   
    networks:
      - escoffier.net

  api:
    restart: always
    build:
      context: ..
      dockerfile: docker/dockerfile
    ports:
      - '${PORT}:${PORT}'
    networks:
      - escoffier.net
    depends_on:
      - db

      

volumes:
  redis-data:
  rabbitmq-data:
  mongodb-data:

networks:
  escoffier.net:
    driver: bridge
