services:

  queues-manager:
    build: ./images/rabbitmq
    restart: always
    hostname: escoffier.queue
    ports:
      - "15673:15672"
      - "5673:5672"

    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASS}
    networks:
      - escoffier.network

  db-restaurant-service:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DBR_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DBR_PASS}
      MONGO_INITDB_DATABASE: ${DBR_NAME}
    volumes:
      - ./volumes-db/db-restaurants:/data/db

    networks:
      - escoffier.restaurant.network


networks:
  escoffier.network:
    driver: bridge
  escoffier.restaurant.network:
    driver: bridge


volumes:
  mongo-data: