services:

  db:
    image: mongo:6.0
    restart: always
    hostname: escoffier.db

    volumes:
      - ./mongo-data:/data/db
  
    networks:
      - escoffier.net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    
    command: [ "--replSet" , "rs0" , "--bind_ip_all" , "--port" , "27017" ] 

  queues:
    image: rabbitmq:management
    restart: always
    hostname: hermes.queue.dev
    ports:
      - '5673:5672'
      - '15673:15672'
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASS}
    networks:
      - escoffier.net

  redis:
    image: redis
    hostname: ${REDIS_HOST}
    volumes:
      - ./redis-data:/data
    restart: always
   
    networks:
      - escoffier.net

  api:
    restart: always
    build:
      context: ..
      dockerfile: docker/dockerfile
    ports:
      - '${PORT}:${PORT}'
    networks:
      - escoffier.net
    depends_on:
      - db

      

volumes:
  redis-data:
  rabbitmq-data:
  mongodb-data:

networks:
  escoffier.net:
    driver: bridge
