export enum ResponsesEnum{
    INVALID_MAIL = "E-mail inválido",
    MAIL_REQUIRED = "E-mail é requerido",
   
    INVALID_NAME = "Nome inválido",
    NAME_REQUIRED = "Nome é requerido",
   
    INVALID_PASSWORD = "Senha inválida",
    PASSWORD_REQUIRED = "Senha é requerida",
    
    INVALID_PROFILE = "Perfil inválido",
   
    INVALID_MENU_NAME = "Nome do menu inválido",
    MENU_NAME_REQUIRED = "Nome do menu é requerido",
  
    INVALID_CATEGORY_NAME = "Nome da categoria inválido",
    CATEGORY_NAME_REQUIRED = "Nome da categoria é requerido",
   
    INVALID_DISHE_NAME = "Nome do prato inválido",
    DISHE_NAME_REQUIRED = "Nome do prato é requerido",
   
    INVALID_DISHE_PRICE = "Preço do prato inválido",
    DISHE_PRICE_REQUIRED = "Preço do prato é requerido",
    
    INVALID_DISHE_MODE = "Modo do prato inválido",
    DISHE_MODE_REQUIRED = "Modo do prato é requerido",
   
    DISHE_DESCRIPTION_REQUIRED = "Descrição do prato é requerida",
   
    DISHE_CATEGORY_REQUIRED = "Categoria do prato é requerida",
    
    INVALID_IMAGE = "Imagem inválida",
    NAME_IS_LONG = "NAME_IS_LONG",
    NAME_IS_SHORT = "NAME_IS_SHORT",
    PASSWORD_IS_SHORT = "PASSWORD_IS_SHORT",
    PASSWORD_IS_LONG = "PASSWORD_IS_LONG",
    RESTAURANT_ALREADY_EXISTS = "RESTAURANT_ALREADY_EXISTS",
    REGISTERED_RESTAURANT = "REGISTERED_RESTAURANT",
    RESTAURANT_NOT_FOUND = "RESTAURANT_NOT_FOUND",
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
    LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
    RESUME_IS_LONG = "RESUME_IS_LONG",
    RESUME_IS_SHORT = "RESUME_IS_SHORT",
    VERIFY_CODE_TO_NEW_EMAIL = "VERIFY_CODE_TO_NEW_EMAIL",
    UPDATED_INFO = "UPDATED_INFO",
    PROFILE_UPDATED = "PROFILE_UPDATED",
    VERIFY_CODE_TO_EMAIL = "VERIFY_CODE_TO_EMAIL",
    NOT_HAVE_CHANGES = "NOT_HAVE_CHANGES",
    INVALID_CODE = "INVALID_CODE",
    DELETED_RESTAURANT = "DELETED_RESTAURANT",
    ACCESS_DENIED = "ACCESS_DENIED",
    MENU_NAME_ALREADY_EXISTS = "MENU_NAME_ALREADY_EXISTS",
    MENU_CREATED = "MENU_CREATED",
    MENU_NOT_FOUND = "MENU_NOT_FOUND",
    MENU_DELETED = "MENU_DELETED",
    MENU_UPDATED = "MENU_UPDATED",
    MANY_BOOLEAN_IS_REQUIRED = "MANY_BOOLEAN_IS_REQUIRED",
    INVALID_ID = "INVALID_ID",
    INVALID_BODY_OF_REQUEST = "INVALID_BODY_OF_REQUEST",
    EMAIL_OR_NAME_ALREADY_EXISTS = "EMAIL_OR_NAME_ALREADY_EXISTS",
    CATEGORY_ALREADY_EXISTS_IN_MENU = "CATEGORY_ALREADY_EXISTS_IN_MENU",
    CATEGORY_CREATED = "CATEGORY_CREATED",
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
    CATEGORY_DELETED = "CATEGORY_DELETED",
    ID_REQUIRED = "ID_REQUIRED",
    DISHE_NOT_FOUND = "DISHE_NOT_FOUND",
    DISHE_DELETED = "DISHE_DELETED",
    DISHE_IMAGE_UPLOADED = "DISHE_IMAGE_UPLOADED"

}